- name: Install golang
  package:
    name: "{{ snowflake_packages_deb }}"
    default_release: bullseye
    state: present

- name: Install required software
  package:
    name: "{{ snowflake_utils }}"
    state: present
