- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Install golang
  package:
    name: "{{ snowflake_packages_deb_ubuntu }}"
    state: present

- name: Install required software
  package:
    name: "{{ snowflake_utils }}"
    state: present
